const countryData = [
  // ===== ASEAN =====
  { name: "Thailand", flag: "https://flagcdn.com/w320/th.png" },
  { name: "Vietnam", flag: "https://flagcdn.com/w320/vn.png" },
  { name: "Malaysia", flag: "https://flagcdn.com/w320/my.png" },
  { name: "Indonesia", flag: "https://flagcdn.com/w320/id.png" },
  { name: "Singapore", flag: "https://flagcdn.com/w320/sg.png" },
  { name: "Philippines", flag: "https://flagcdn.com/w320/ph.png" },
  { name: "Cambodia", flag: "https://flagcdn.com/w320/kh.png" },
  { name: "Laos", flag: "https://flagcdn.com/w320/la.png" },
  { name: "Myanmar", flag: "https://flagcdn.com/w320/mm.png" },
  { name: "Brunei", flag: "https://flagcdn.com/w320/bn.png" },

  // ===== EUROPE =====
  { name: "United Kingdom", flag: "https://flagcdn.com/w320/gb.png" },
  { name: "France", flag: "https://flagcdn.com/w320/fr.png" },
  { name: "Germany", flag: "https://flagcdn.com/w320/de.png" },
  { name: "Italy", flag: "https://flagcdn.com/w320/it.png" },
  { name: "Spain", flag: "https://flagcdn.com/w320/es.png" },
  { name: "Portugal", flag: "https://flagcdn.com/w320/pt.png" },
  { name: "Netherlands", flag: "https://flagcdn.com/w320/nl.png" },
  { name: "Belgium", flag: "https://flagcdn.com/w320/be.png" },
  { name: "Switzerland", flag: "https://flagcdn.com/w320/ch.png" },
  { name: "Austria", flag: "https://flagcdn.com/w320/at.png" },
  { name: "Sweden", flag: "https://flagcdn.com/w320/se.png" },
  { name: "Norway", flag: "https://flagcdn.com/w320/no.png" },
  { name: "Denmark", flag: "https://flagcdn.com/w320/dk.png" },
  { name: "Finland", flag: "https://flagcdn.com/w320/fi.png" },
  { name: "Poland", flag: "https://flagcdn.com/w320/pl.png" },
  { name: "Czech Republic", flag: "https://flagcdn.com/w320/cz.png" },
  { name: "Greece", flag: "https://flagcdn.com/w320/gr.png" },
  { name: "Hungary", flag: "https://flagcdn.com/w320/hu.png" },
  { name: "Romania", flag: "https://flagcdn.com/w320/ro.png" },
  { name: "Ukraine", flag: "https://flagcdn.com/w320/ua.png" }
];
